# Generated by Django 5.1.7 on 2025-05-13 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='hora_fin_atencion',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='hora_inicio_atencion',
            field=models.TimeField(default=datetime.time(17, 0)),
            preserve_default=False,
        ),
    ]
