# Generated by Django 5.1.7 on 2025-05-13 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('fechafactura', models.DateField(auto_now_add=True)),
                ('formapago', models.CharField(max_length=50)),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('idcita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='cita.cita')),
            ],
        ),
    ]
