# Generated by Django 5.1.7 on 2025-05-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sedes.sede'),
        ),
    ]
