# Generated by Django 5.1.7 on 2025-05-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_estado_persona_sede'),
        ('sedes', '0002_sede_hora_fin_atencion_sede_hora_inicio_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='sede',
        ),
        migrations.AddField(
            model_name='personalsalud',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sedes.sede'),
        ),
    ]
